# Services
services:
    _defaults:
        autowire: true
        autoconfigure: true

    NetGroup\DataTransformationLayer\Classes\Engine\ProjectionRegistry:
        arguments:
            $projections: !tagged_iterator 'netgroup.datatransformation.projection'

    NetGroup\DataTransformationLayer\Classes\Engine\DatasetTransformer:
        arguments:
            $converterLocator: !tagged_locator 'netgroup.datatransformation.converter'

    # Factories
    NetGroup\DataTransformationLayer\Classes\Services\Factories\DefinitionFactory: ~

    # Helper
    NetGroup\DataTransformationLayer\Classes\Services\Helper\TransforamtionHelper: ~